### ISSUE TITLE
where can I find the pre-trained model data?

### ISSUE THREAD

**Issue by alexfs** [maxmelichov/Text-To-speech#1]
This fails  to download:

force_download_TT2 = True
tacotron2_pretrained_model = 'MLPTTS'
if not exists(tacotron2_pretrained_model) or force_download_TT2:
                   # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ PUT MODEL HERE
  gdown.download(d+r'1ByWFnQsqIZuJpz7PgBgCo4ED63eFyKKp&export=download', tacotron2_pretrained_model, quiet=False); print("Tacotron2 Model Downloaded")
                   # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ PUT MODEL HERE

waveglow_pretrained_model = 'waveglow.pt'
if not exists(waveglow_pretrained_model):
  gdown.download(d+r'1rpK8CzAAirq9sWZhe9nlfvxMF1dRgFbF&export=download', waveglow_pretrained_model, quiet=False); print("WaveGlow Model Downloaded")#1okuUstGoBe_qZ4qUEF8CcwEugHP7GM_b&export

**Comment by maxmelichov** [comment]
Thanks for noticing, I uploaded a new link for the model.

**Comment by alexfs** [comment]
where's the link?

**Comment by maxmelichov** [comment]
You have a new link to the file on the Colab.

**Comment by alexfs** [comment]
You didn't do any commits, am I missing something?

**Comment by maxmelichov** [comment]
In Google Colab, it saves automatically.  If you like, I can share the link in the README.
